### ISSUE TITLE
Consider changing `sync()` to something more accurate (e.g. `pull()`)

### ISSUE THREAD

**Issue by CodingDoug** [libsql/libsql-js#21]
Synchronization often suggests a two-way sync between two copies of data.  What seems to be implemented here is a one-way "pull" of data missing in the embedded replica.  Clients periodically "pull" new data into the database (similar to a git pull), and there is no concept of local changes to be pushed up to the service, since those are always delegated to the service.

**Comment by penberg** [comment]
I believe the `sync()` name is correct and future-proof because we certainly want to be able to sync to the other direction as well.
